%YAML:1.0
#########################################
#  图像选项
#########################################
# 数据库根目录位置：该目录下应该有rgb_index/和dep_index/两个文件夹，记录了rgb图与深度度
data_source: /home/y/code/dataset/fr1_room
# 图像特征的检测算子与描述算子的名称
detector_name: STAR
descriptor_name: SIFT
# 数据的起始编号与结束编号
start_index: 1
end_index: 1352
# 是否在灰度图中处理数据：暂不支持颜色信息
grayscale: yes
# 两帧相邻图像描述子之间最小匹配距离
match_min_dist: 5
# 每一次循环的等待时间（毫秒）
step_time: 10
# 发现关键帧时等待时间
step_time_keyframe: 100
# 相邻两帧的最大距离，超过此距离则放弃该帧
error_threshold: 0.8

# feature manager
#连续看见多少帧则记录至仓库
save_if_seen: 1
# 新特征，未连续出现多少帧则从缓存删除（建议该参数设置大一些，以实现全局匹配）
del_not_seen: 20
# 是否为没有深度数据的点设置最大深度
set_max_depth: yes
# 最大深度
max_depth: 20
# 每一帧最最多匹配的路标上限
max_landmark_per_loop: 100

#########################################
#  图优化选项
#########################################
# 优化步数
optimize_step: 10
# robust核函数
robust_kernel: Cauchy
# 最大位移，超过此位移后需要全局优化,认为出现关键帧
max_pos_change: 0.2

#########################################
#  其他选项
#########################################
# 是否在线生成点云图（较耗时间）
online_pcl: yes
# 栅格大小
grid_leaf: 0.05
# 是否使用FAB-MAP 2.0
fabmap: no

#########################################
#  3D SLAM 选项
#########################################
# 提取平面时的距离阈值 （越大表示平面的精度越粗糙）
distance_threshold: 0.05 
# 平面点的百分比
plane_percent: 0.3
# 归类图像点时的误差阈值（较大时会把离平面较远的点也算在平面上）
min_error_plane: 0.02
# 最大平面数量
max_planes: 4
# 是否使用闭环
loop_closure_detection: yes
# 闭环检测随机取多少帧
loopclosure_frames: 20
# 闭环检测误差阈值（离过去关键帧某个距离之内才算正确的闭环）
loop_closure_error: 2.0
# 丢失判定（连续若干帧以上匹配不到算作丢失）
lost_frames: 5

#########################################
#  相机参数
#########################################
camera_fx: 517.0
camera_fy: 517.0
camera_cx: 318.6
camera_cy: 255.3
camera_factor: 5000.0
